name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - 
        name: "Build:checkout"
        uses: actions/checkout@v2
      -
        name: Build and Push to GHCR
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: go-http
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
